# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "sinatra", "~> 2.0"

gem "unicorn", "~> 5.5"

gem "tzinfo-data", "= 1.2019.3"
